---
#限流开关
limter.flow.enabled: false
---
#文件加载的环境配置
spring:
  profiles:
    active: test
  application:
    name: user

---
#端口
server:
  port: 8087

#开启熔断机制
feign.hystrix.enabled: true

---
#mybatis的扫包路径
mybatis:
  typeAliasesPackage: com.e_commerce.miscroservice.user.po,com.e_commerce.miscroservice.xiaoshi_proj.order.po

---
#打开数据库配置
open.datasource: true
flyway.enabled: false


---
#mq管理
mq:
  #是否打开发送开关 true是 false不是
  openSend: true
  # 发送消息的集合管理  格式  消息名称:消息的类型(fanout,direct):接受的监听类的名称(首字母小写) eg msg:fanout:demoListener   timer_scheduler_timer_accept_order_overtime_pay:fanout:orderPayListener:true
  channels: timer_scheduler_timer_accept_order_overtime_end:fanout:orderEndListener,
    timer_scheduler_timer_accept_order_overtime_pay:fanout:orderPayListener,
    timer_scheduler_timer_accept_order_send_message:fanout:orderSendMessageListener,
    timer_scheduler_timer_accept_order_overtime_remark:fanout:orderRemarkListener,
    timer_scheduler_timer_accept_remove_order_punishment:fanout:orderRemovePunishmentListener,
    timer_scheduler_timer_accept_bonus_package_send_back_task:fanout:bonusPackageListener:true



#一些配置
#二维码 -> 小程序page值
page:
  #邀请好友
  invite: pages/help/help
  #个人主页
  person: package/my/pages/home/home
  #服务
  service: package/index/pages/helpServiceDetail/helpServiceDetail
  #求助
  help: package/index/pages/helpServiceDetail/helpServiceDetail
  #组织
  company: package/my/pages/sureJoinOrganize/sureJoinOrganize
  #报名页面
  join: package/my/pages/sureJoinOrganize/sureJoinOrganize

---
#debug
debug: true

---
#微信正式
wechat:
  app_id: wx0fc132bec055b894
  app_secret: d29e69777caab57d7aa0bc3000b5e220

---
#短信模版
smsTemplate: \u0025\u0073\u662f\u60a8\u672c\u6b21\u7684\u9a8c\u8bc1\u7801\uff0c\u8bf7\u52ff\u6cc4\u9732\u7ed9\u4ed6\u4eba\uff0c\u5341\u5206\u949f\u4e4b\u5185\u6709\u6548\u3002\u3010\u6653\u65f6\u4e92\u52a9\u3011

---
#用户hash前缀
redis_user: timebank_user_test
redis_score: score_test

---
# Redis 开发版本使用5号库
spring.redis.database: 5
spring.redis.host: 120.27.208.177
spring.redis.password: 1234
---
logging:
  level:
   com.e_commerce.miscroservice.commons.helper.plug.mybatis.mapper: debug

