FROM java
VOLUME /tmp
ADD ./build/libs/miscroservice*.jar /miscroservice.jar
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ENTRYPOINT [ "sh", "-c", "java -Djava.security.egd=file:/dev/./urandom -Dremote.log.level=INFO  -Xms512m -Xmx1024m -jar /miscroservice.jar" ]
